theme: jekyll-theme-minimal
title: DeepBlue-X
description: Here contains a list of articles I published.
logo: http://icons.iconarchive.com/icons/cjdowner/cryptocurrency-flat/256/DeepBrain-Chain-DBC-icon.png
show_downloads: "true"
google_analytics: [Your Google Analytics tracking ID]
